<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\apifestivos.aplicacion\apifestivos.aplicacion.csproj" />
    <ProjectReference Include="..\apifestivos.core\apifestivos.core.csproj" />
    <ProjectReference Include="..\apifestivos.dominio\apifestivos.dominio.csproj" />
    <ProjectReference Include="..\apifestivos.infraestructura\apifestivos.infraestructura.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

</Project>
